version: '3.8'

services:
  dnscrypt-proxy:
    image: klutchell/dnscrypt-proxy:latest
    container_name: dnscrypt-proxy
    ports:
      - 127.0.0.1:53:53/tcp
      - 127.0.0.1:53:53/udp
      - "[::1]:53:53/tcp"
      - "[::1]:53:53/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml:ro
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always
